title: Ecommerce Edge
description: Tactical ecommerce and conversion strategies
theme: minima
baseurl: "/ecommerceedge"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
