title: Ecommerce Edge
description: Tactical ecommerce and conversion strategies
theme: minima
baseurl: ""
url: "https://ecommerceedge.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
